plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

tasks.register('prepareKotlinBuildScriptModel') {

}

android {
    namespace 'ru.runa.wfe'
    compileSdk 35
    flavorDimensions = ["version"]

    defaultConfig {
        applicationId "ru.runa.wfe"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        buildConfig = true
    }
    productFlavors {
        original {
            dimension "version"
            versionNameSuffix = "-v1"
        }
        parallel {
            dimension "version"
            versionNameSuffix = "-v2"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation "androidx.activity:activity-ktx:1.10.1"
    implementation 'androidx.browser:browser:1.8.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

}